apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      # nodeSelector:
      #   node: minikube
      containers:
      - name: autoscaler-container
        image: ghcr.io/mike911209/autoscaler:local
        ports:
        - containerPort: 8080
        env:
        - name: METRICS_SCRAPE_INTERVAL
          value: "10"  # 2 minutes in seconds
        imagePullPolicy: Always # to check if registry get new image, else it will always pull the same image version
      # imagePullSecrets:  
      #   - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-service
  namespace: default
  labels:
    app: autoscaler
spec:
  selector:
    app: autoscaler
  ports:
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: autoscaler
    release: prometheus
  name: autoscaler-servicemonitor
  namespace: default
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app: autoscaler
---
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: autoscaler
#   namespace: default
# spec:
#   template:
#     spec:
#       serviceAccountName: autoscaler-sa
#       containers:
#         - name: autoscaler-container
#           image: ghcr.io/mike911209/autoscaler:latest
#           ports:
#             - containerPort: 8080
#           env:
#           - name: METRICS_SCRAPE_INTERVAL
#             value: "10"  # 2 minutes in seconds
#           imagePullPolicy: Always # to check if registry get new image, else it will always pull the same image version
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["serving.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoscaler
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: default
  labels:
    app: autoscaler
data:
  metrics: |
    - name: tgi_request_metric
      query: increase(tgi_request_mean_time_per_token_duration_sum{pod="%s"}[1m])/increase(tgi_request_mean_time_per_token_duration_count{pod="%s"}[1m])
      slo: 0.5
      scaleDownFactor: 0.5
      scaleUpFactor: 1.5