apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-10-15T02:50:09Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.1.4
    helm.sh/chart: grafana-8.4.6
  name: prometheus-grafana
  namespace: monitoring
  resourceVersion: "41228794"
  uid: ce0b5656-35b4-4ba1-a657-d320baedb1b5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: grafana-volume
  volumeMode: Filesystem
  volumeName: grafana-volume
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  phase: Bound
