apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce # required
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-volume
  hostPath:
     path: /net/storage149/autofs/css89
