apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  labels:
    prometheus: volume
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteOnce # required
  persistentVolumeReclaimPolicy: Retain
  hostPath:
     path: /net/storage149/autofs/css89
